# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'restart_quote.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(316, 246)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
        MainWindow.setIconSize(QtCore.QSize(24, 21))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lab_title = QtWidgets.QLabel(self.centralwidget)
        self.lab_title.setGeometry(QtCore.QRect(20, 10, 241, 41))
        font = QtGui.QFont()
        font.setFamily("SetoFont")
        font.setPointSize(18)
        self.lab_title.setFont(font)
        self.lab_title.setObjectName("lab_title")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(20, 170, 75, 23))
        font = QtGui.QFont()
        font.setFamily("SetoFont")
        font.setPointSize(12)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.env = QtWidgets.QComboBox(self.centralwidget)
        self.env.setGeometry(QtCore.QRect(120, 120, 100, 23))
        self.env.addItems(['OTP-GW','JGX-GW','TS-GW','JGX-Risk','TS-Risk','JGX-Relay','TS-Relay','OTP-Relay','PB-Adapter','OTP-Quote-All','JGX-Quote-All','TS-Quote-All'])
        #self.env.addItems(['1','2','3'])                                                            #下拉選單
        self.env.setObjectName("env")
        self.lab_username = QtWidgets.QLabel(self.centralwidget)
        self.lab_username.setGeometry(QtCore.QRect(20, 50, 101, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.lab_username.setFont(font)
        self.lab_username.setObjectName("lab_username")
        self.lab_password = QtWidgets.QLabel(self.centralwidget)
        self.lab_password.setGeometry(QtCore.QRect(20, 80, 101, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.lab_password.setFont(font)
        self.lab_password.setObjectName("lab_password")
        self.txt_username = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_username.setGeometry(QtCore.QRect(120, 60, 113, 20))
        self.txt_username.setObjectName("txt_username")
        self.txt_password = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_password.setGeometry(QtCore.QRect(120, 90, 113, 20))
        self.txt_password.setObjectName("txt_password")
        self.lab_env = QtWidgets.QLabel(self.centralwidget)
        self.lab_env.setGeometry(QtCore.QRect(20, 110, 101, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.lab_env.setFont(font)
        self.lab_env.setObjectName("lab_env")
        self.lab_state = QtWidgets.QLabel(self.centralwidget)
        self.lab_state.setGeometry(QtCore.QRect(130, 160, 161, 31))
        font = QtGui.QFont()
        font.setFamily("SetoFont")
        font.setPointSize(14)
        self.lab_state.setFont(font)
        self.lab_state.setText("")
        self.lab_state.setObjectName("lab_state")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.env.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

#外觀介面改這邊
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "一通數位有限公司"))
        self.lab_title.setText(_translate("MainWindow", "交易系統行情報價重啟"))
        self.submit.setText(_translate("MainWindow", "執行"))
        self.lab_username.setText(_translate("MainWindow", "使用者帳號"))
        self.lab_password.setText(_translate("MainWindow", "登入密碼"))
        self.lab_env.setText(_translate("MainWindow", "執行環境"))
