: > /home/version3.0/icelog/routine/BaseIceBox-1.err
: > /home/version3.0/icelog/routine/BaseIceBox-1.out
: > /home/version3.0/icelog/routine/CamIceBox-1.err
: > /home/version3.0/icelog/routine/CamIceBox-1.out
: > /home/version3.0/icelog/routine/CrmIceBox-1.err
: > /home/version3.0/icelog/routine/CrmIceBox-1.out
: > /home/version3.0/icelog/routine/RbacIceBox-1.err
: > /home/version3.0/icelog/routine/RbacIceBox-1.out
: > /home/version3.0/icelog/routine/TradeIceBox-1.err
: > /home/version3.0/icelog/routine/TradeIceBox-1.out
: > /home/version3.0/icelog/routine/BrokerCommissionIceBox-1.err
: > /home/version3.0/icelog/routine/BrokerCommissionIceBox-1.out
: > /home/version3.0/icelog/routine/ConfigIceBox-1.err
: > /home/version3.0/icelog/routine/ConfigIceBox-1.out
: > /home/version3.0/icelog/routine/FollowIceBox-1.err
: > /home/version3.0/icelog/routine/FollowIceBox-1.out
: > /home/version3.0/icelog/routine/SupportIceBox-1.err
: > /home/version3.0/icelog/routine/SupportIceBox-1.out
: > /home/version3.0/icelog/routine/CamExtIceBox-1.err
: > /home/version3.0/icelog/routine/CamExtIceBox-1.out
: > /home/version3.0/icelog/routine/CostIceBox-1.err
: > /home/version3.0/icelog/routine/CostIceBox-1.out
: > /home/version3.0/icelog/routine/FsrIceBox-1.err
: > /home/version3.0/icelog/routine/FsrIceBox-1.out
: > /home/version3.0/icelog/routine/TradeClIceBox-1.err
: > /home/version3.0/icelog/routine/TradeClIceBox-1.out

: > /home/version3.0/icelog/gateway/ConfigService1.err
: > /home/version3.0/icelog/gateway/ConfigService1.out
: > /home/version3.0/icelog/gateway/RbacService1.err
: > /home/version3.0/icelog/gateway/RbacService1.out
: > /home/version3.0/icelog/gateway/SupportService1.err
: > /home/version3.0/icelog/gateway/SupportService1.out
