---
- hosts: testjava
  remote_user: root

  tasks:
    - name: mkdir /src
      file:
        path: /src
        state: directory

    - name: chmod +x /etc/rc.d/rc.local
      shell:
        cmd: "chmod +x /etc/rc.d/rc.local"

    - name: install epel-release
      yum:
        name:
          - epel-release
        state: latest
        update_cache: yes

    - name: Disable SELinux
      selinux:
        state: disabled

#    - name: set selinux disabled
#      shell:
#        cmd: "sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config"

    - name: Disable Firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: install rpm
      yum:
        name:
          - vim
          - wget
          - net-tools
          - openssl
          - openssh-clients
          - openssl-devel
          - ntp
          - gcc
          - gcc-c++
          - lrzsz
          - kernel-devel
          - kernel-headers
          - kernel
          - zip
          - unzip
          - man
          - time
          - glibc-devel
          - glibc-headers
          - xorg-x11-font-utils
          - xorg-x11-fonts-Type1
          - xorg-x11-server-Xorg
          - xorg-x11-xauth
          - xorg-x11-apps
          - telnet
          - bind-utils
          - samba
          - samba-client
          - samba-common
          - nfs-utils
          - psmisc
        state: present

    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present

    - name: Yum update the system
      yum:
        name: "*"
        state: latest

    - name: Install the Zabbix rpm from a remote repo
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        state: present

#    - name: install zabbix-agent repo
#      shell:
#        cmd: "rpm -ivh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm"

    - name: install zabbix-agent2 and zabbix-get
      yum:
        name:
          - zabbix-agent2
          - zabbix-get
        state: present

    - name: cp zabbix-agent.conf
      copy:
        src: /home/ansbile/zabbix/zabbix_agent2.conf
        dest: /etc/zabbix/zabbix_agent2.conf

    - name: Chown /etc/zabbix Zabbix
      ansible.builtin.file:
        path: /etc/zabbix
        owner: zabbix
        group: zabbix

#    - name: chown zabbix for /etc/zabbix
#      shell:
#        cmd: "chown -R zabbix:zabbix /etc/zabbix"

    - name: start zabbix-agent2
      ansible.builtin.systemd:
        name: zabbix-agent2
        state: started
        enabled: yes

    - name: Rebooting......
      reboot:

    - name: Use NTP
      shell:
        cmd: ntpdate time.stdtime.gov.tw

    - name: setting NTP crontab
      cron:
        name: "NTP crontab"
        minute: "10"
        hour: "5"
        job: "root (/usr/sbin/ntpdate time.stdtime.gov.tw && /sbin/hwclock -w) &> /dev/null"
