---
- hosts: nginx
  remote_user: root

  tasks:
    - name: set hostname /etc/sysconfig/network
      replace:
        path: /etc/sysconfig/network
        regexp: '^HOSTNAME=localhost.localdomain'
        replace: 'HOSTNAME=tomcat02'

    - name: set hostname /etc/hosts
      shell:
        cmd: "sed -i 's/localhost.localdomain/tomcat02/g'"

    - name: set selinux disabled
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=enforcing'
        replace: 'SELINUX=disabled'

    - name: Flush iptables
      shell:
        cmd: iptables -F

    - name: copy CentOS Repo
      copy:
        src: /home/ansbile/centos6/CentOS-Base.repo
        dest: /etc/yum.repos.d/CentOS-Base.repo

    - name: install epel-repo
      yum:
        name:
          - vim
          - wget
          - net-tools
          - openssl
          - openssh-clients
          - psmisc
          - epel-release
          - ntp
          - gcc
          - lrzsz
          - kernel-devel
          - kernel-headers
          - kernel
          - zip
          - unzip
          - man
          - time
          - at
          - bc
          - ed
          - glibc-devel
          - glibc-headers
          - gtk2
          - cvs
          - xorg-x11-font-utils
          - xorg-x11-fonts-Type1
          - alsa-lib
          - gettext
          - giflib
          - jpackage-utils
          - libICE
          - libSM
          - libXfont
          - libXtst
          - libart_lgpl
          - libfontenc
          - libgcj
          - lksctp-tools
          - patch
          - pcsc-lite-libs
          - ttmkfdir
          - libmpc-devel
          - mpfr-devel
          - gmp-devel
          - xorg-x11-server-Xorg
          - xorg-x11-xauth
          - xorg-x11-apps
        state: latest

    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present

    - name: Yum update the system
      yum:
        name: "*"
        state: latest

    - name: Rebooting......
      reboot:

    - name: Use NTP
      shell:
        cmd: ntpdate time.stdtime.gov.tw

    - name: setting NTP crontab
      cron:
        name: "NTP crontab"
        minute: "10"
        hour: "5"
        job: "root (/usr/sbin/ntpdate time.stdtime.gov.tw && /sbin/hwclock -w) &> /dev/null"

    - name: install nginx
      yum:
        name: nginx
        state: latest

    - name: copy nginx config file
      copy:
        src: /home/ansbile/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: copy nginx config directory
      copy:
        src: /home/ansbile/nginx/conf.d/
        dest: /etc/nginx/conf.d/

    - name: touch Nginx access log
      copy:
        src: /home/ansbile/nginx/log/
        dest: /var/log/nginx/log/
        owner: nginx

    - name: restart nginx
      service:
        name: nginx
        state: restarted
