---
- hosts: newcpp
  remote_user: root

  tasks:
#    - name: set hostname /etc/sysconfig/network
#      replace:
#        path: /etc/sysconfig/network
#        regexp: '^HOSTNAME=localhost.localdomain'
#        replace: 'HOSTNAME=tomcat02

#    - name: set selinux disabled
#      shell:
#        cmd: "sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config"

#    - name: Rebooting......
#      reboot:

    - name: mkdir /src
      file:
        path: /src
        state: directory

    - name: mkdir /home/version3.0
      file:
        path: /home/version3.0
        state: directory

    - name: Add group iceuser
      ansible.builtin.group:
        name: iceuser

    - name: Add the user ICE
      user: 
        name: iceuser
        groups: iceuser
        password: "{{ 'icepass' | password_hash('sha512') }}"

#    - name: copy CentOS Repo
#      copy:
#        src: /home/ansbile/centos6/CentOS-Base.repo
#        dest: /etc/yum.repos.d/CentOS-Base.repo

#    - name: copy script to /src
#      copy:
#        src: /home/ansbile/tomcat/script/
#        dest: /src/

#    - name: copy ice script tp /src
#      copy:
#        src: /home/ansbile/ice/
#        dest: /src/

    - name: install epel-release
      yum:
        name:
          - epel-release
        state: latest
        update_cache: yes

#    - name: copy cpp file to /home/version3.0
#      copy:
#        src: /home/ansbile/cpp/version3.0
#        dest: /home/version3.0

    - name: chown iceuser for /home/version3.0
      shell:
        cmd: "chown -R iceuser:iceuser /home/version3.0"

    - name: Flush iptables
      shell:
        cmd: iptables -F

    - name: install rpm
      yum:
        name:
          - vim
          - wget
          - net-tools
          - openssl
          - openssh-clients
          - psmisc
          - ntp
          - gcc
          - lrzsz
          - kernel-devel
          - kernel-headers
          - kernel
          - zip
          - unzip
          - man
          - time
          - glibc-devel
          - glibc-headers
          - gtk2
          - xorg-x11-font-utils
          - xorg-x11-fonts-Type1
          - alsa-lib
          - gettext
          - giflib
          - jpackage-utils
          - libICE
          - libSM
          - libXfont
          - libXtst
          - libart_lgpl
          - libfontenc
          - libgcj
          - lksctp-tools
          - patch
          - pcsc-lite-libs
          - ttmkfdir
          - libmpc-devel
          - mpfr-devel
          - gmp-devel
          - xorg-x11-server-Xorg
          - xorg-x11-xauth
          - xorg-x11-apps
          - libmcpp-devel
          - bzip2-devel
          - db4-devel
          - expat-devel
          - openssl-devel
        state: present

    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present

    - name: wget ice repo
      shell:
        cmd: "wget -P /etc/yum.repos.d/ https://zeroc.com/download/Ice/3.6/el7/zeroc-ice3.6.repo"

    - name: yum install mcpp-devel
      yum:
        name:
          - mcpp-devel
        state: present
        update_cache: yes

    - name: Yum update the system
      yum:
        name: "*"
        state: latest

    - name: Rebooting......
      reboot:

    - name: Use NTP
      shell:
        cmd: ntpdate time.stdtime.gov.tw

    - name: setting NTP crontab
      cron:
        name: "NTP crontab"
        minute: "10"
        hour: "5"
        job: "root (/usr/sbin/ntpdate time.stdtime.gov.tw && /sbin/hwclock -w) &> /dev/null"

    - name: install gcc
      shell:
        cmd: "sh /src/install_gcc630.sh"

    - name: copy libstdc++ to /usr/lib64
      copy:
        src: /home/ansbile/ice/libstdc++.so.6
        dest: /usr/lib64/

#    - name: install nvm
#      shell: 
#        cmd: "sh /src/install_nvm_ionic.sh"
     
#    - name: nvm
#      shell: 
#        cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
#      args:
#        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: copy jdk-8u281-linux-x64.tar.gz to /src
      copy:
        src: /home/ansbile/tomcat/jdk-8u281-linux-x64.tar.gz
        dest: /src/jdk-8u281-linux-x64.tar.gz

    - name: install jdk 281
      shell:
        cmd: "sh /src/jdk_install.sh"

#    - name: install maven
#      shell:
#        cmd: "sh /src/maven_install.sh"

#    - name: install ice
#      shell:
#        cmd: "sh /src/install_ice.sh"
