---
- hosts: new
  remote_user: root

  tasks:
    - name: mkdir /var/www/html
      file:
        path: /var/www/html
        state: directory

    - name: mkdir /var/www/yii
      file:
        path: /var/www/yii
        state: directory

    - name: copy nginx.repo
      copy:
        src: /home/ansbile/php/nginx.conf
        dest: /etc/yum.repos.d/nginx.conf

    - name: copy php.repo
      copy:
        src: /home/ansbile/php/php.conf
        dest: /etc/nginx/conf.d/php.conf

    - name: copy php.repo
      copy:
        src: /home/ansbile/php/composer.phar
        dest: /var/www/composer.phar

    - name: install remi rpm
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

    - name: install mysql rpm
      yum:
        name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
        state: present

    - name: disable php54
      shell:
        cmd: "yum-config-manager --disable remi-php54"

    - name: enable php73
      shell:
        cmd: "yum-config-manager --enable remi-php73"

    - name: install rpm
      yum:
        name:
          - php
          - php-cli
          - php-fpm
          - php-mysqlnd
          - php-zip
          - php-devel
          - php-gd
          - php-mcrypt
          - php-mbstring
          - php-curl
          - php-xml 
          - php-pear
          - php-bcmath
          - php-json
          - mysql-community-server
          - nginx
        state: present

    - name: Enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Enable php-fpm
      systemd:
        name: php-fpm
        state: started
        enabled: yes

    - name: Enable Mysql
      systemd:
        name: mysqld
        state: started
        enabled: yes

    - name: enable php73
      shell:
        cmd: php /var/www/composer.phar global require "fxp/composer-asset-plugin:1.0.0-beta3"



    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present

    - name: Yum update the system
      yum:
        name: "*"
        state: latest

    - name: Install the Zabbix rpm from a remote repo
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        state: present

#    - name: install zabbix-agent repo
#      shell:
#        cmd: "rpm -ivh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm"

    - name: install zabbix-agent2 and zabbix-get
      yum:
        name:
          - zabbix-agent2
          - zabbix-get
        state: present

    - name: cp zabbix-agent.conf
      copy:
        src: /home/ansbile/zabbix/zabbix_agent2.conf
        dest: /etc/zabbix/zabbix_agent2.conf

    - name: Chown /etc/zabbix Zabbix
      ansible.builtin.file:
        path: /etc/zabbix
        owner: zabbix
        group: zabbix

#    - name: chown zabbix for /etc/zabbix
#      shell:
#        cmd: "chown -R zabbix:zabbix /etc/zabbix"

    - name: start zabbix-agent2
      ansible.builtin.systemd:
        name: zabbix-agent2
        state: started
        enabled: yes

    - name: Rebooting......
      reboot:

    - name: Use NTP
      shell:
        cmd: ntpdate time.stdtime.gov.tw

    - name: setting NTP crontab
      cron:
        name: "NTP crontab"
        minute: "10"
        hour: "5"
        job: "root (/usr/sbin/ntpdate time.stdtime.gov.tw && /sbin/hwclock -w) &> /dev/null"
